name: bam:bus
info: Welcome to Bambus Theme
pygments: true
paginate: 4

navigation:
- text: About
  title: About bambus
  url: /
  icon: icon-leaf
- text: Wiki
  title: Getting started
  url: https://github.com/MyRealityCoding/muffin-bambus#muffin-bambus
  icon: icon-book
- text: Author
  title: About the author
  url: http://my-reality.de
  icon: icon-user
- text: Social
  title: bambus on Facebook
  url: http://facebook.com/bambus
  icon: icon-facebook-sign
- text: Download
  title: Download recent version
  url: https://github.com/MyRealityCoding/muffin-bambus/archive/master.zip
  icon: icon-download-alt
  
author:
  name: Miguel Gonzalez
  email: miguel-gonzalez@gmx.de
  url: https://github.com/MyRealityCoding/muffin-bambus#muffin-bambus
  label: "Getting started >"
  description: Bambus is a minimal and clean theme for <a href="http://jekyllrb.com/">Jekyll</a>, built on the top of <a href="http://www.richbray.me/muffin">Muffin</a>.
  image: /img/bambus-icon.png
  
links:
- url: http://jekyllrb.com
  name: Jekyll
- url: http://www.richbray.me/muffin/#feat
  name: Muffin
- url: http://my-reality.de
  name: Blog
